
create_clock -name sys_clk -period 20.000 -waveform {0.000 10.000} -add [get_ports clk]
create_clock -name eth_rxclk -period 8 -waveform {0.000 4.000} [get_ports e_rxc]

set_property PACKAGE_PIN M22 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets {clk_IBUF}]

set_property PACKAGE_PIN H7 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]

set_property PACKAGE_PIN E3 [get_ports rs232_tx_data_o]
set_property IOSTANDARD LVCMOS33 [get_ports rs232_tx_data_o]
#set_property PACKAGE_PIN F3 [get_ports rs232_rx_data_i]
#set_property IOSTANDARD LVCMOS33 [get_ports rs232_rx_data_i]
set_property PACKAGE_PIN AB26 [get_ports ad_clk_o]
set_property IOSTANDARD LVCMOS33 [get_ports ad_clk_o]

set_property PACKAGE_PIN AC26 [get_ports ad_data_i[0]]
set_property IOSTANDARD LVCMOS33 [get_ports ad_data_i[0]]
set_property PACKAGE_PIN AB24 [get_ports ad_data_i[1]]
set_property IOSTANDARD LVCMOS33 [get_ports ad_data_i[1]]
set_property PACKAGE_PIN AC24 [get_ports ad_data_i[2]]
set_property IOSTANDARD LVCMOS33 [get_ports ad_data_i[2]]
set_property PACKAGE_PIN AA24 [get_ports ad_data_i[3]]
set_property IOSTANDARD LVCMOS33 [get_ports ad_data_i[3]]
set_property PACKAGE_PIN AB25 [get_ports ad_data_i[4]]
set_property IOSTANDARD LVCMOS33 [get_ports ad_data_i[4]]
set_property PACKAGE_PIN AA22 [get_ports ad_data_i[5]]
set_property IOSTANDARD LVCMOS33 [get_ports ad_data_i[5]]
set_property PACKAGE_PIN AA23 [get_ports ad_data_i[6]]
set_property IOSTANDARD LVCMOS33 [get_ports ad_data_i[6]]
set_property PACKAGE_PIN Y25 [get_ports ad_data_i[7]]
set_property IOSTANDARD LVCMOS33 [get_ports ad_data_i[7]]
set_property PACKAGE_PIN AA25 [get_ports ad_data_i[8]]
set_property IOSTANDARD LVCMOS33 [get_ports ad_data_i[8]]
set_property PACKAGE_PIN W25 [get_ports ad_data_i[9]]
set_property IOSTANDARD LVCMOS33 [get_ports ad_data_i[9]]
set_property PACKAGE_PIN Y26 [get_ports ad_data_i[10]]
set_property IOSTANDARD LVCMOS33 [get_ports ad_data_i[10]]
set_property PACKAGE_PIN Y22 [get_ports ad_data_i[11]]
set_property IOSTANDARD LVCMOS33 [get_ports ad_data_i[11]]
set_property PACKAGE_PIN Y23 [get_ports ad_data_i[12]]
set_property IOSTANDARD LVCMOS33 [get_ports ad_data_i[12]]

set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 [current_design]

set_property IOSTANDARD LVCMOS33 [get_ports {e_rxd[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e_rxd[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e_rxd[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e_rxd[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e_rxd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e_rxd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e_rxd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e_rxd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e_txd[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e_txd[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e_txd[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e_txd[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e_txd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e_txd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e_txd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {e_txd[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports e_txer]
set_property IOSTANDARD LVCMOS33 [get_ports e_txen]
set_property IOSTANDARD LVCMOS33 [get_ports e_txc]
set_property IOSTANDARD LVCMOS33 [get_ports e_rxer]
set_property IOSTANDARD LVCMOS33 [get_ports e_rxdv]
set_property IOSTANDARD LVCMOS33 [get_ports e_rxc]
set_property IOSTANDARD LVCMOS33 [get_ports e_rst]
set_property IOSTANDARD LVCMOS33 [get_ports e_mdio]
set_property IOSTANDARD LVCMOS33 [get_ports e_mdc]
set_property IOSTANDARD LVCMOS33 [get_ports e_gtxc]
set_property PACKAGE_PIN U1 [get_ports e_gtxc]
set_property PACKAGE_PIN H2 [get_ports e_mdc]
set_property PACKAGE_PIN H1 [get_ports e_mdio]
set_property PACKAGE_PIN R1 [get_ports e_rst]
set_property PACKAGE_PIN P4 [get_ports e_rxc]
set_property PACKAGE_PIN L3 [get_ports e_rxdv]
set_property PACKAGE_PIN U5 [get_ports e_rxer]
set_property PACKAGE_PIN M2 [get_ports e_txc]
set_property PACKAGE_PIN T2 [get_ports e_txen]
set_property PACKAGE_PIN J1 [get_ports e_txer]
set_property PACKAGE_PIN R2 [get_ports {e_txd[0]}]
set_property PACKAGE_PIN P1 [get_ports {e_txd[1]}]
set_property PACKAGE_PIN N2 [get_ports {e_txd[2]}]
set_property PACKAGE_PIN N1 [get_ports {e_txd[3]}]
set_property PACKAGE_PIN M1 [get_ports {e_txd[4]}]
set_property PACKAGE_PIN L2 [get_ports {e_txd[5]}]
set_property PACKAGE_PIN K2 [get_ports {e_txd[6]}]
set_property PACKAGE_PIN K1 [get_ports {e_txd[7]}]
set_property PACKAGE_PIN M4 [get_ports {e_rxd[0]}]
set_property PACKAGE_PIN N3 [get_ports {e_rxd[1]}]
set_property PACKAGE_PIN N4 [get_ports {e_rxd[2]}]
set_property PACKAGE_PIN P3 [get_ports {e_rxd[3]}]
set_property PACKAGE_PIN R3 [get_ports {e_rxd[4]}]
set_property PACKAGE_PIN T3 [get_ports {e_rxd[5]}]
set_property PACKAGE_PIN T4 [get_ports {e_rxd[6]}]
set_property PACKAGE_PIN T5 [get_ports {e_rxd[7]}]
